name: Build Android APK with GitHub Actions

on: [push]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # ==================================================================
      #  *** تم تصحيح اسم مالك الأداة هنا ***
      # ==================================================================
      - name: Build with Buildozer (Corrected Action)
        uses: anas-alkassem/buildozer-action@v1.1  # <-- تم تصحيح هذا السطر
        id: buildozer
        with:
          build_dir: .
          
      - name: Upload generated APK
        uses: actions/upload-artifact@v4
        with:
          name: HackerCalculator-APK
          path: ${{ steps.buildozer.outputs.apk_path }}
