name: Build Kivy APK (Final Attempt)

on: [push]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # ==================================================================
      #  *** التغيير المهم هنا ***
      #  نعود إلى الإصدار v1 مع إضافة متغير بيئة لحل مشكلة chown
      # ==================================================================
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          buildozer_version: "1.5.0"
          command: "buildozer android debug"
          # هذا السطر يخبر الأداة بتجاوز خطوة تغيير الملكية التي تسبب الخطأ
          user: "root" 
          
      - name: Upload generated APK
        uses: actions/upload-artifact@v4
        with:
          name: HackerCalculator-APK
          path: ${{ steps.buildozer.outputs.filename }}
