name: Build with Official Kivy Action
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # تثبيت Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # تثبيت الاعتماديات
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer cython==0.29.33
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev \
            libgstreamer1.0 \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            openjdk-17-jdk \
            unzip

      # ==================================================================
      #  *** التغيير المهم هنا: إعداد البيئة والموافقة على التراخيص ***
      #  سنقوم بتعريف المسارات والموافقة في نفس الخطوة لضمان التعرف عليها
      # ==================================================================
      - name: Setup Android Environment & Accept Licenses
        run: |
          # إنشاء المسارات
          export ANDROID_HOME="$HOME/android-sdk"
          export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH"
          
          # إنشاء مجلدات SDK
          mkdir -p $ANDROID_HOME/cmdline-tools
          
          # تنزيل وفك ضغط أدوات سطر الأوامر
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-9477386_latest.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          
          # الموافقة على التراخيص
          echo "y" | sdkmanager "platform-tools" "platforms;android-31"
          yes | sdkmanager --licenses
          
          # تصدير المسارات إلى خطوات العمل التالية
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "PATH=$PATH" >> $GITHUB_ENV

      # بناء APK
      - name: Build APK with Buildozer
        run: |
          buildozer android debug

      # رفع ملف APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: HackerCalculator-APK
          path: .buildozer/android/platform/build-*/outputs/apk/debug/*.apk
