name: Build Kivy APK (Modern)

on: [push]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@1.2.1  # <-- تم تصحيح هذا السطر
        id: buildozer
        with:
          buildozer_version: "1.5.0"
          command: "buildozer android debug"
          
      - name: Upload generated APK
        uses: actions/upload-artifact@v4
        with:
          name: HackerCalculator-APK
          path: ${{ steps.buildozer.outputs.filename }}
